### ISSUE TITLE
Scan frequency drop

### ISSUE THREAD

**Issue by MoffKalast** [UbiquityRobotics/ld06_lidar#1]
After a few minutes of runtime the laserscan publishing frequency seems to drop lower and lower until it's useless for mapping.

![what](https://user-images.githubusercontent.com/9977799/159298852-66b027ca-f0e1-4189-b192-f2039bfc5fa9.gif)
EZ-Map always renders the transforms sequentially, so in this case it shows odom movement while rviz is waiting for a new map transform which just isn't arriving.

```
ubuntu@bot:~$ rostopic hz scan
subscribed to [/bot/scan]
no new messages
no new messages
no new messages
no new messages
no new messages
no new messages
no new messages
no new messages
no new messages
average rate: 0.240
        min: 4.174s max: 4.174s std dev: 0.00000s window: 2
no new messages
no new messages
no new messages
average rate: 0.238
        min: 4.174s max: 4.214s std dev: 0.01959s window: 3
no new messages
no new messages
no new messages
average rate: 0.239
        min: 4.163s max: 4.214s std dev: 0.02150s window: 4
no new messages
no new messages
no new messages
average rate: 0.240
        min: 4.100s max: 4.214s std dev: 0.04085s window: 5
no new messages
no new messages
no new messages
average rate: 0.240
        min: 4.100s max: 4.222s std dev: 0.04350s window: 6
no new messages
no new messages
no new messages
no new messages
average rate: 0.240
        min: 4.100s max: 4.222s std dev: 0.04802s window: 7
no new messages
no new messages
average rate: 0.242
        min: 3.917s max: 4.222s std dev: 0.09664s window: 8
no new messages
no new messages
no new messages
average rate: 0.243
        min: 3.917s max: 4.222s std dev: 0.09277s window: 9
no new messages
no new messages

```

Could be something to do with the USB to serial board or the USB controller or with the driver itself. I suppose the question is does it happen when the lidar is directly attached to the Pi? 

Restarting the driver seems to reset it, but it happens again after a few minutes.

**Comment by JanezCim** [comment]
Maybe try with a different driver if there are others out there?
